services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

        Mindy\Bundle\DashboardBundle\Dashboard\WidgetInterface:
            public: true
            tags: ['dashboard.widget']

    Mindy\Bundle\DashboardBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'
